from pydantic import BaseModel, HttpUrl


# Schema used when the client creates a new monitor.
# It contains only the fields the client is allowed to provide.
class MonitorCreate(BaseModel):
    name: str
    url: HttpUrl


# Schema used when the API returns a single monitor.
# The ID is included because it is generated by the database.
class MonitorResponse(BaseModel):
    id: int
    name: str
    url: HttpUrl

    # Allows Pydantic to read data directly from SQLAlchemy objects.
    model_config = {"from_attributes": True}

class MonitorUpdate(BaseModel):
    name:str
    url:HttpUrl

# Schema for the complete response of GET /monitors/.
# It wraps multiple MonitorResponse objects inside a "monitors" field.
class MonitorListResponse(BaseModel):
    monitors: list[MonitorResponse]